import os

BASE_DIR = "./api/"
MAX_ATTEMPTS = 100
DIMENSION = 4
IMAGES_DIR= BASE_DIR + "images/"
OBJECTS_SVG_DIR = BASE_DIR + "objects/"
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
DB_USER = os.getenv("MYSQL_USER")
DB_PASSWORD = os.getenv("MYSQL_PASSWORD")
DB_PORT = os.getenv("MYSQL_PORT")
DB_NAME = os.getenv("MYSQL_DATABASE")
JWT_ALGORITHM = "HS256"
TOKEN_VALIDITY_TIME = 30
print(DB_USER, DB_PORT, DB_PASSWORD, DB_NAME)